import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/common/Navbar";
import { Footer } from "@/components/common/Footer";
import { Toaster } from "react-hot-toast";
import SessionServerProvider from "@/components/common/SessionServerProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Toaster position="top-center" reverseOrder={false} />
        <SessionServerProvider />
        <Footer />
      </body>
    </html>
  );
}
